<?php
$arrTher = array (
		'id',
		'patient_id',
		'visit_id',
		'chmt_karboplatin_yes_no_id',
		'chmt_cisplatin_yes_no_id',
		'chmt_ciklofosfan_yes_no_id',
		'chmt_paklitaksel_yes_no_id',
		'chmt_doksorubicin_yes_no_id',
		'chmt_topotekan_yes_no_id',
		'chmt_gemcitabin_yes_no_id',
		'chmt_vinorelbin_yes_no_id',
		'chmt_irinotekan_yes_no_id',
		'chmt_jetopozid_yes_no_id',
		'chmt_jepirubicin_yes_no_id',
		'chmt_docetaksel_yes_no_id',
		'chmt_oksaliplatin_yes_no_id',
		'chmt_other_yes_no_id',
		'chmt_other_descr',
		'chmt_date_start',
		'chmt_date_finish',
		'instr_kt_yes_no_id',
		'instr_kt_date',
		'instr_kt_norm_yes_no_id',
		'instr_kt_descr',
		'instr_mrt_yes_no_id',
		'instr_mrt_date',
		'instr_mrt_norm_yes_no_id',
		'instr_mrt_descr',
		'instr_petkt_yes_no_id',
		'instr_petkt_date',
		'instr_petkt_norm_yes_no_id',
		'instr_petkt_descr',
		'targeted_therapy_yes_no_id',
		'targeted_therapy_erlotinib_yes_no_id',
		'targeted_therapy_gefitinib_yes_no_id',
		'targeted_therapy_cryotinib_yes_no_id',
		'targeted_therapy_nivolumab_yes_no_id',
		'targeted_therapy_other_yes_no_id',
		'targeted_therapy_descr',
		'side_effects_yes_no_id',
		'side_effects_descr',
		'hb_before_ct',
		'hb_before_ct_date',
		'erythrocytes_before_ct',
		'erythrocytes_before_ct_date',
		'leuc_before_ct',
		'leuc_before_ct_date',
		'tromb_before_ct',
		'tromb_before_ct_date',
		'neutr_before_ct',
		'neutr_before_ct_date',
		'gen_prot_before_ct',
		'gen_prot_before_ct_date',
		'ast_before_ct',
		'ast_before_ct_date',
		'alt_before_ct',
		'alt_before_ct_date',
		'bilirubin_before_ct',
		'bilirubin_before_ct_date',
		'creat_before_ct',
		'creat_before_ct_date',
		'urea_before_ct',
		'urea_before_ct_date',
		'neurotoxicity_yes_no_id',
		'neurotoxicity_level_id',
		'skin_toxicity_yes_no_id',
		'skin_toxicity_level_id',
		'user',
		'insert_date'
);

$arr_pat = array (
		"id",
		"patient_number",
		"hospital_id",
		"date_start_invest",
		"doctor",
		"inclusion_criteria_years_more18_yes_no_id",
		"inclusion_criteria_diag_conf_histo_yes_no_id",
		"inclusion_criteria_diag_conf_cyto_yes_no_id",
		"inclusion_criteria_diag_conf_clin_radio_yes_no_id",
		"inclusion_criteria_got_antitumor_therapy_yes_no_id",
		"exclusion_criteria_not_got_antitumor_therapy_yes_no_id",
		"date_birth",
		"sex_id",
		"place_living_id",
		"social_status_id",
		"diag_cancer_estab_date",
		"cytologic_conclusion",
		"diag_cancer_histotype",
		"immunohistochemical_study_id",
		"immunohistochemical_study_descr",
		"genetic_study_yes_no_id",
		"genetic_study_fish",
		"genetic_study_pcr",
		"diag_cancer_tnm_stage_t_id",
		"diag_cancer_tnm_stage_n_id",
		"diag_cancer_tnm_stage_m_id",
		"diag_cancer_clin_stage_id",
		"diag_cancer_ecog_status_id",
		"instr_kt_yes_no_id",
		"instr_kt_date",
		"instr_kt_norm_yes_no_id",
		"instr_kt_descr",
		"instr_mrt_yes_no_id",
		"instr_mrt_date",
		"instr_mrt_norm_yes_no_id",
		"instr_mrt_descr",
		"instr_petkt_yes_no_id",
		"instr_petkt_date",
		"instr_petkt_norm_yes_no_id",
		"instr_petkt_descr",
		"instr_radiotherapy_yes_no_id",
		"instr_radiotherapy_type",
		"instr_radiotherapy_start_date",
		"instr_radiotherapy_end_date",
		"instr_radiotherapy_kt_yes_no_id",
		"instr_radiotherapy_kt_date",
		"instr_radiotherapy_kt_norm_yes_no_id",
		"instr_radiotherapy_kt_descr",
		"instr_radiotherapy_mrt_yes_no_id",
		"instr_radiotherapy_mrt_date",
		"instr_radiotherapy_mrt_norm_yes_no_id",
		"instr_radiotherapy_mrt_descr",
		"instr_radiotherapy_petkt_yes_no_id",
		"instr_radiotherapy_petkt_date",
		"instr_radiotherapy_petkt_norm_yes_no_id",
		"instr_radiotherapy_petkt_descr",
		"patient_status_last_visit_date",
		"patient_status_id",
		"patient_if_died_date",
		"patient_if_died_cause_id",
		"patient_if_died_cause_descr",
		"user",
		"insert_date" 
);

$arr_ther_kv = array (
		'patient_id' => 'Пациент',
		'visit_id' => 'Номер визита',
		'chmt_karboplatin_id' => 'Химиотерапия: Карбоплатин (да, нет)',
		'chmt_cisplatin_id' => 'Химиотерапия: Цисплатин (да, нет)',
		'chmt_ciklofosfan_id' => 'Химиотерапия: Циклофосфан (да, нет)',
		'chmt_paklitaksel_id' => 'Химиотерапия: Паклитаксел (да, нет)',
		'chmt_doksorubicin_id' => 'Химиотерапия: Доксорубицин (да, нет)',
		'chmt_topotekan_id' => 'Химиотерапия: Топотекан (да, нет)',
		'chmt_gemcitabin_id' => 'Химиотерапия: Гемцитабин (да, нет)',
		'chmt_vinorelbin_id' => 'Химиотерапия: Винорельбин (да, нет)',
		'chmt_irinotekan_id' => 'Химиотерапия: Иринотекан (да, нет)',
		'chmt_jetopozid_id' => 'Химиотерапия: Этопозид (да, нет)',
		'chmt_jepirubicin_id' => 'Химиотерапия: Эпирубицин (да, нет)',
		'chmt_docetaksel_id' => 'Химиотерапия: Доцетаксел (да, нет)',
		'chmt_oksaliplatin_id' => 'Химиотерапия: Оксалиплатин (да, нет)',
		'chmt_trabektedin_id' => 'Химиотерапия: Трабектедин (да, нет)',
		'chmt_other_id' => 'Химиотерапия: Другое (да, нет)',
		'chmt_other_descr' => 'Химиотерапия: Другое (описание)',
		'chmt_date_start' => 'Химиотерапия: Дата начала лечения',
		'chmt_date_finish' => 'Химиотерапия: Дата окончания лечения',
		'diaganem_afterchmt_hb' => 'Лабораторные исследования после химиотерапии: Гемоглобин',
		'diaganem_afterchmt_hb_date' => 'Лабораторные исследования после химиотерапии: Дата проведения гемоглобина',
		'diaganem_afterchmt_erythrocytes' => 'Лабораторные исследования после химиотерапии: Эритроциты',
		'diaganem_afterchmt_lab_erythrocytes_date' => 'Лабораторные исследования после химиотерапии: Дата проведения Эритроциты',
		'epoetin_yes_no_id' => 'Эпоэтины: да, нет',
		'epoetin_eprex40k_dstart' => 'Эпоэтины: Эпрекс 40K (дата начала)',
		'epoetin_eprex40k_dfinish' => 'Эпоэтины: Эпрекс 40K (дата завершения)',
		'epoetin_eprex40k_trfinish_yes_no_id' => 'Эпоэтины: Эпрекс 40K  лечение прекращено (да, нет)',
		'epoetin_eprex40k_trfinish_cause_id' => 'Эпоэтины: Эпрекс 40K лечение - причина прекращения',
		'epoetin_eprex2k5ML_dstart' => 'Эпоэтины: Эпрекс 2K 5ML (дата начала)',
		'epoetin_eprex2k5ML_dfinish' => 'Эпоэтины: Эпрекс 2K 5ML (дата завершения)',
		'epoetin_eprex2k5ML_trfinish_yes_no_id' => 'Эпоэтины: Эпрекс 2K 5ML  лечение прекращено (да, нет)',
		'epoetin_eprex2k5ML_trfinish_cause_id' => 'Эпоэтины: Эпрекс 2K 5ML  лечение - причина прекращения',
		'epoetin_rekormon_dstart' => 'Эпоэтины: Рекормон 2000IU (дата начала)',
		'epoetin_rekormon_dfinish' => 'Эпоэтины: Рекормон 2000IU (дата завершения)',
		'epoetin_rekormon_trfinish_yes_no_id' => 'Эпоэтины: Рекормон 2000IU  лечение прекращено (да, нет)',
		'epoetin_rekormon_trfinish_cause_id' => 'Эпоэтины: Рекормон 2000IU  лечение - причина прекращения',
		'epoetin_other_name' => 'Эпоэтины: Другой препарат наименование',
		'epoetin_other_dstart' => 'Эпоэтины: Другой препарат (дата начала)',
		'epoetin_other_dfinish' => 'Эпоэтины: Другой препарат (дата завершения)',
		'epoetin_other_trfinish_yes_no_id' => 'Эпоэтины: Другой препарат  лечение прекращено (да, нет)',
		'epoetin_other_trfinish_cause_id' => 'Эпоэтины: Другой препарат  лечение - причина прекращения',
		'ferrum_yes_no_id' => 'Терапия препаратами железа: да, нет',
		'ferrum_dstart' => 'Терапия препаратами железа: дата начала',
		'ferrum_dfinish' => 'Терапия препаратами железа: дата завершения',
		'notepoetin_yes_no_id' => 'Не эпоэтины: да, нет',
		'notepoetin_drug1_name' => 'Не эпоэтины: Препарат 1 - наименование',
		'notepoetin_drug1_dstart' => 'Не эпоэтины: Препарат 1 (дата начала)',
		'notepoetin_drug1_dfinish' => 'Не эпоэтины: Препарат 1 (дата завершения)',
		'notepoetin_drug1_trfinish_yes_no_id' => 'Не эпоэтины: Препарат 1 лечение прекращено (да, нет)',
		'notepoetin_drug1_trfinish_cause_id' => 'Не эпоэтины: Препарат 1 лечение - причина прекращения',
		'notepoetin_drug2_name' => 'Не эпоэтины: Препарат 2 - наименование',
		'notepoetin_drug2_dstart' => 'Не эпоэтины: Препарат 2 (дата начала)',
		'notepoetin_drug2_dfinish' => 'Не эпоэтины: Препарат 2 (дата завершения)',
		'notepoetin_drug2_trfinish_yes_no_id' => 'Не эпоэтины: Препарат 2 лечение прекращено (да, нет)',
		'notepoetin_drug2_trfinish_cause_id' => 'Не эпоэтины: Препарат 2 лечение - причина прекращения',
		'notepoetin_drug3_name' => 'Не эпоэтины: Препарат 2 - наименование',
		'notepoetin_drug3_dstart' => 'Не эпоэтины: Препарат 2 (дата начала)',
		'notepoetin_drug3_dfinish' => 'Не эпоэтины: Препарат 2 (дата завершения)',
		'notepoetin_drug3_trfinish_yes_no_id' => 'Не эпоэтины: Препарат 2 лечение прекращено (да, нет)',
		'notepoetin_drug3_trfinish_cause_id' => 'Не эпоэтины: Препарат 2 лечение - причина прекращения',
		'diaganem_after_correct_hb' => 'Лабораторные исследования после коррекции: Гемоглобин',
		'diaganem_after_correct_hb_date' => 'Лабораторные исследования после коррекции: Дата проведения гемоглобина',
		'diaganem_after_correct_erythrocytes' => 'Лабораторные исследования после коррекции: Эритроциты',
		'diaganem_after_correct_lab_erythrocytes_date' => 'Лабораторные исследования после коррекции: Дата проведения Эритроциты' 
);

?>