CREATE TABLE `lung_patient` (
  `id` INTEGER(11) NOT NULL AUTO_INCREMENT,
  `patient_number` varchar(10) NOT NULL DEFAULT '' COMMENT 'Номер пациента (уникальный в пределах исследования)',
  `hospital_id` int(11) NOT NULL COMMENT 'Мед. центра откуда материл (справочник)',
  `date_start_invest` date NOT NULL COMMENT 'Дата включения в исследование',
  `doctor` varchar(100) NOT NULL DEFAULT '' COMMENT 'ФИО врача',
  `inclusion_criteria_years_more18_yes_no_id` int(11) DEFAULT '-1' COMMENT 'Пациент 18 лет и старше, с впервые в жизни выявленным НМРЛ в 2015-2016 г.г. (да, нет)',
  `inclusion_criteria_diag_conf_histo_yes_no_id` int(11) DEFAULT '-1' COMMENT 'Диагноз НМРЛ подтвержден гистологически (да, нет)',
  `inclusion_criteria_diag_conf_cyto_yes_no_id` int(11) DEFAULT '-1' COMMENT 'Диагноз НМРЛ подтвержден цитологически (да, нет)',
  `inclusion_criteria_diag_conf_clin_radio_yes_no_id` int(11) DEFAULT '-1' COMMENT 'Диагноз выставлен на основе клинико-рентгенологических данных (да, нет)',
  `inclusion_criteria_got_antitumor_therapy_yes_no_id` int(11) DEFAULT '-1' COMMENT 'Пациент, получавший любой вид противоопухолевой терапии в 2015-2017 г.г. (хирургический, химиотерапевтический, таргетрная терапия, лучевая терапия) (да, нет)',
  `exclusion_criteria_not_got_antitumor_therapy_yes_no_id` int(11) DEFAULT '-1' COMMENT 'Пациенты с впервые выявленным НМРЛ, но не получившие ни один из видов противоопухолевой терапии из-за наличия сопутствующей патологии или взятые на учет посмертно (да, нет)',
  `date_birth` date NOT NULL COMMENT 'Дата рождения',
  `sex_id` int(11) NOT NULL DEFAULT '-1' COMMENT 'Пол',
  `place_living_id` int(11) NOT NULL DEFAULT '-1' COMMENT 'Место жительства',
  `social_status_id` int(11) NOT NULL DEFAULT '-1' COMMENT 'Социальный статус',
  `diag_cancer_estab_date` date NOT NULL COMMENT 'Дата постановки диагноза рак',
  `cytologic_conclusion` varchar(255) NOT NULL DEFAULT '' COMMENT 'Цитологическое заключение',
  `diag_cancer_histotype` varchar(100) NOT NULL DEFAULT '' COMMENT 'Гистологический тип опухоли',
  `immunohistochemical_study_id` int(11) NOT NULL DEFAULT '-1' COMMENT 'Иммуногистохимическое исследование',
  `genetic_study_yes_no_id` int(11) NOT NULL DEFAULT '-1' COMMENT 'Генетические исследования (да, нет)',
  `genetic_study_fish` varchar(255) NOT NULL DEFAULT '' COMMENT 'FISH результат',
  `genetic_study_pcr` varchar(255) NOT NULL DEFAULT '' COMMENT 'ПЦР результат',
  `diag_cancer_tnm_stage_t_id` int(11) NOT NULL DEFAULT '-1' COMMENT 'Стадия заболевания по системе TNM - T',
  `diag_cancer_tnm_stage_n_id` int(11) NOT NULL DEFAULT '-1' COMMENT 'Стадия заболевания по системе TNM - N',
  `diag_cancer_tnm_stage_m_id` int(11) NOT NULL DEFAULT '-1' COMMENT 'Стадия заболевания по системе TNM - M',
  `diag_cancer_clin_stage_id` int(11) NOT NULL DEFAULT '-1' COMMENT 'Клиническая стадия заболевания',
  `diag_cancer_ecog_status_id` int(11) NOT NULL DEFAULT '-1' COMMENT 'ECOG статус на момент постановки диагноза и начала лечения',
  
  `instr_kt_yes_no_id` INTEGER(11) NOT NULL DEFAULT '-1' COMMENT 'Инструментальные исследования: КТ да/нет',
  `instr_kt_date` DATE DEFAULT NULL COMMENT 'Инструментальные исследования: КТ дата',
  `instr_kt_norm_yes_no_id` INTEGER(11) NOT NULL DEFAULT '-1' COMMENT 'Инструментальные исследования: КТ норма/патология',
  `instr_kt_descr` VARCHAR(255) COLLATE utf8_general_ci DEFAULT NULL COMMENT 'Инструментальные исследования: КТ Заключение',
  
  `instr_mrt_yes_no_id` INTEGER(11) NOT NULL DEFAULT '-1' COMMENT 'Инструментальные исследования: МРТ да/нет',
  `instr_mrt_date` DATE DEFAULT NULL COMMENT 'Инструментальные исследования: МРТ дата',
  `instr_mrt_norm_yes_no_id` INTEGER(11) NOT NULL DEFAULT '-1' COMMENT 'Инструментальные исследования: МРТ норма/патология',
  `instr_mrt_descr` VARCHAR(255) COLLATE utf8_general_ci DEFAULT NULL COMMENT 'Инструментальные исследования: МРТ Заключение',
  
  `instr_petkt_yes_no_id` INTEGER(11) NOT NULL DEFAULT '-1' COMMENT 'Инструментальные исследования: ПЭТ-КТ да/нет',
  `instr_petkt_date` DATE DEFAULT NULL COMMENT 'Инструментальные исследования: ПЭТ-КТ дата',
  `instr_petkt_norm_yes_no_id` INTEGER(11) NOT NULL DEFAULT '-1' COMMENT 'Инструментальные исследования: ПЭТ-КТ норма/патология',
  `instr_petkt_descr` VARCHAR(255) COLLATE utf8_general_ci DEFAULT NULL COMMENT 'Инструментальные исследования: ПЭТ-КТ Заключение',

  `instr_radiotherapy_yes_no_id` INTEGER(11) NOT NULL DEFAULT '-1' COMMENT 'Лучевая терапия да/нет',
  `instr_radiotherapy_type` VARCHAR(255) COLLATE utf8_general_ci DEFAULT NULL COMMENT 'ЛУЧЕВАЯ ТЕРАПИЯ: вид, РОД, СОД и пр.',
  `instr_radiotherapy_start_date` DATE DEFAULT NULL COMMENT 'Лучевая терапия: дата начала',
  `instr_radiotherapy_end_date` DATE DEFAULT NULL COMMENT 'Лучевая терапия: дата завершения',
  
  `instr_radiotherapy_kt_yes_no_id` INTEGER(11) NOT NULL DEFAULT '-1' COMMENT 'Лучевая терапия: Инструментальные исследования: КТ да/нет',
  `instr_radiotherapy_kt_date` DATE DEFAULT NULL COMMENT 'Лучевая терапия: Инструментальные исследования: КТ дата',
  `instr_radiotherapy_kt_norm_yes_no_id` INTEGER(11) NOT NULL DEFAULT '-1' COMMENT 'Лучевая терапия: Инструментальные исследования: КТ норма/патология',
  `instr_radiotherapy_kt_descr` VARCHAR(255) COLLATE utf8_general_ci DEFAULT NULL COMMENT 'Лучевая терапия: Инструментальные исследования: КТ Заключение',
  
  `instr_radiotherapy_mrt_yes_no_id` INTEGER(11) NOT NULL DEFAULT '-1' COMMENT 'Лучевая терапия: Инструментальные исследования: МРТ да/нет',
  `instr_radiotherapy_mrt_date` DATE DEFAULT NULL COMMENT 'Лучевая терапия: Инструментальные исследования: МРТ дата',
  `instr_radiotherapy_mrt_norm_yes_no_id` INTEGER(11) NOT NULL DEFAULT '-1' COMMENT 'Лучевая терапия: Инструментальные исследования: МРТ норма/патология',
  `instr_radiotherapy_mrt_descr` VARCHAR(255) COLLATE utf8_general_ci DEFAULT NULL COMMENT 'Лучевая терапия: Инструментальные исследования: МРТ Заключение',
  
  `instr_radiotherapy_petkt_yes_no_id` INTEGER(11) NOT NULL DEFAULT '-1' COMMENT 'Лучевая терапия: Инструментальные исследования: ПЭТ-КТ да/нет',
  `instr_radiotherapy_petkt_date` DATE DEFAULT NULL COMMENT 'Лучевая терапия: Инструментальные исследования: ПЭТ-КТ дата',
  `instr_radiotherapy_petkt_norm_yes_no_id` INTEGER(11) NOT NULL DEFAULT '-1' COMMENT 'Лучевая терапия: Инструментальные исследования: ПЭТ-КТ норма/патология',
  `instr_radiotherapy_petkt_descr` VARCHAR(255) COLLATE utf8_general_ci DEFAULT NULL COMMENT 'Лучевая терапия: Инструментальные исследования: ПЭТ-КТ Заключение',
  
  `user` varchar(25) DEFAULT NULL,
  `insert_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `lung_therapy` (
  `id` INTEGER(11) NOT NULL AUTO_INCREMENT,
  `patient_id` int(11) NOT NULL COMMENT 'Пациент',
  `visit_id` int(11) NOT NULL COMMENT 'Номер визита',
  `chmt_karboplatin_id` int(11) DEFAULT '-1' COMMENT 'Химиотерапия: Карбоплатин (да, нет)',
  `chmt_cisplatin_id` int(11) NOT NULL DEFAULT '-1' COMMENT 'Химиотерапия: Цисплатин (да, нет)',
  `chmt_ciklofosfan_id` int(11) NOT NULL DEFAULT '-1' COMMENT 'Химиотерапия: Циклофосфан (да, нет)',
  `chmt_paklitaksel_id` int(11) NOT NULL DEFAULT '-1' COMMENT 'Химиотерапия: Паклитаксел (да, нет)',
  `chmt_doksorubicin_id` int(11) NOT NULL DEFAULT '-1' COMMENT 'Химиотерапия: Доксорубицин (да, нет)',
  `chmt_topotekan_id` int(11) NOT NULL DEFAULT '-1' COMMENT 'Химиотерапия: Топотекан (да, нет)',
  `chmt_gemcitabin_id` int(11) NOT NULL DEFAULT '-1' COMMENT 'Химиотерапия: Гемцитабин (да, нет)',
  `chmt_vinorelbin_id` int(11) NOT NULL DEFAULT '-1' COMMENT 'Химиотерапия: Винорельбин (да, нет)',
  `chmt_irinotekan_id` int(11) NOT NULL DEFAULT '-1' COMMENT 'Химиотерапия: Иринотекан (да, нет)',
  `chmt_jetopozid_id` int(11) NOT NULL DEFAULT '-1' COMMENT 'Химиотерапия: Этопозид (да, нет)',
  `chmt_jepirubicin_id` int(11) NOT NULL DEFAULT '-1' COMMENT 'Химиотерапия: Эпирубицин (да, нет)',
  `chmt_docetaksel_id` int(11) NOT NULL DEFAULT '-1' COMMENT 'Химиотерапия: Доцетаксел (да, нет)',
  `chmt_oksaliplatin_id` int(11) NOT NULL DEFAULT '-1' COMMENT 'Химиотерапия: Оксалиплатин (да, нет)',
  `chmt_other_id` int(11) NOT NULL DEFAULT '-1' COMMENT 'Химиотерапия: Другое (да, нет)',
  `chmt_other_descr` varchar(50) DEFAULT NULL COMMENT 'Химиотерапия: Другое (описание)',
  `chmt_date_start` date DEFAULT NULL COMMENT 'Химиотерапия: Дата начала лечения',
  `chmt_date_finish` date DEFAULT NULL COMMENT 'Химиотерапия: Дата окончания лечения',
    
  `instr_kt_yes_no_id` INTEGER(11) NOT NULL DEFAULT '-1' COMMENT 'Инструментальные исследования: КТ да/нет',
  `instr_kt_date` DATE DEFAULT NULL COMMENT 'Инструментальные исследования: КТ дата',
  `instr_kt_norm_yes_no_id` INTEGER(11) NOT NULL DEFAULT '-1' COMMENT 'Инструментальные исследования: КТ норма/патология',
  `instr_kt_descr` VARCHAR(255) COLLATE utf8_general_ci DEFAULT NULL COMMENT 'Инструментальные исследования: КТ Заключение',
  
  `instr_mrt_yes_no_id` INTEGER(11) NOT NULL DEFAULT '-1' COMMENT 'Инструментальные исследования: МРТ да/нет',
  `instr_mrt_date` DATE DEFAULT NULL COMMENT 'Инструментальные исследования: МРТ дата',
  `instr_mrt_norm_yes_no_id` INTEGER(11) NOT NULL DEFAULT '-1' COMMENT 'Инструментальные исследования: МРТ норма/патология',
  `instr_mrt_descr` VARCHAR(255) COLLATE utf8_general_ci DEFAULT NULL COMMENT 'Инструментальные исследования: МРТ Заключение',
  
  `instr_petkt_yes_no_id` INTEGER(11) NOT NULL DEFAULT '-1' COMMENT 'Инструментальные исследования: ПЭТ-КТ да/нет',
  `instr_petkt_date` DATE DEFAULT NULL COMMENT 'Инструментальные исследования: ПЭТ-КТ дата',
  `instr_petkt_norm_yes_no_id` INTEGER(11) NOT NULL DEFAULT '-1' COMMENT 'Инструментальные исследования: ПЭТ-КТ норма/патология',
  `instr_petkt_descr` VARCHAR(255) COLLATE utf8_general_ci DEFAULT NULL COMMENT 'Инструментальные исследования: ПЭТ-КТ Заключение',
  
  `user` varchar(25) DEFAULT NULL,
  `insert_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;